name: rfc1751
version: 0.1.4
synopsis: RFC-1751 library for Haskell
description: Please see the README on GitHub at <https://github.com/jprupp/rfc1751#readme>
category: Crypto
author: JP Rupp
maintainer: jprupp@protonmail.ch
license: MIT
license-file: LICENSE
github: xenog/rfc1751.git
dependencies:
  - bytestring
  - cereal
  - vector
library:
  source-dirs:
    - src
  dependencies:
    - base ==4.*
tests:
  test-rfc1751:
    main: Spec.hs
    source-dirs:
      - tests
    ghc-options: -Wall
    dependencies:
      - base
      - hspec
      - rfc1751
      - QuickCheck
